name = "radio3-playlist"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# Cron trigger - runs daily at 9 AM UTC
[triggers]
crons = ["0 9 * * *"]

# Environment variables (non-sensitive)
[vars]
SPOTIFY_REDIRECT_URL = "http://localhost:3000/spotify/auth"

# Secrets (set via: wrangler secret put <KEY>)
# SPOTIFY_CLIENT_ID
# SPOTIFY_CLIENT_SECRET
# SPOTIFY_ACCESS_TOKEN
# SPOTIFY_REFRESH_TOKEN
