name = "radio3-playlist"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# Cron triggers - each podcast runs at different times to avoid "Too many subrequests" error
# Turbo3: 9:00 AM UTC
# Na na na: 9:05 AM UTC
# 180 grados: 9:10 AM UTC
[triggers]
crons = ["0 9 * * *", "5 9 * * *", "10 9 * * *"]

# Environment variables (non-sensitive)
[vars]
SPOTIFY_REDIRECT_URL = "http://localhost:3000/spotify/auth"

# Secrets (set via: wrangler secret put <KEY>)
# SPOTIFY_CLIENT_ID
# SPOTIFY_CLIENT_SECRET
# SPOTIFY_ACCESS_TOKEN
# SPOTIFY_REFRESH_TOKEN

[observability]
enabled = true
head_sampling_rate = 1
